### ISSUE TITLE
Taille des images en automatique

### ISSUE THREAD

**Issue by cokecorp** [Salvialf/StatutBin#1]
Pouvoir avoir la possibilité de modifier la taille des icones 30x30 50x50 64x64 90x90

**Comment by Salvialf** [comment]
OK c'est fait ! 
Possibilité de choisir la taille de l'icône via l'ajout d'un paramètre optionnel "nom:taille"-"valeur:90" (exemple) donnera une icône de 90px*90px. Si pas de paramètre "taille" l'icône sera à sa taille originale.
+ Possibilité d'ajouter un paramètre optionnel "nom:name"-"valeur:tv" (exemple) pour prise en compte de l'icône sans avoir à modifier le nom de la commande.
